ospfranco/react-native-quick-sqlite

cpp/sequel.cpp
example/src/Database.ts

Fixes #3 
Using `.length()` calculates the correct amount of length for strings when inserting into SQLite database. This fixes the unicode encoding issue.
`.length()` from the cpp string class is a bit faster since it's already cached in the instance when initialized, so no need to recalculate it.

Use .length() for length calculation in c

---

README.md
cpp/sequel.cpp

More details on the issue: https://github.com/ospfranco/react-native-quick-sqlite/issues/16

Use `double` over `int32` for representing numbers when retrieving data from sqlite

---

cpp/sqlite3.h

- SQLite version upgraded to 3.38.0
This version brings some performance optmizations and
JSON functions are now enabled by default

SQLite version upgrade

---

cpp/sequel.cpp

- Small bugfix on the "rowsAffected" property, that was
collecting all changes on database instance since its
opening instead of the current statement.

rowsAffected - Bugfix

---

cpp/SequelResult.h
cpp/react-native-quick-sqlite.cpp
cpp/sequel.cpp
cpp/sequel.h
src/index.ts

Hi @ospfranco . How are you?
I've made some tests in order to find better ways to handle large bulk operations, and I wanna know if you have any interest in a way to "import sql files" directly from the native code:
- This feature allows fast "import" of SQL Files directly
from a absolute path, on the C++ code, avoiding parsing
large jsons or files via JavaScript in order to dispach
calls to library. Some tests with datasets ~120k rows
shows an improvment of at least 35% over the bulk update
feature (PR 24).
- Small bugfix on the "rowsAffected" property, that was
collecting all changes on database instance since its
opening instead of the current statement.

[Proposal]: SQL Loader Feature

---

android/CMakeLists.txt
cpp/JSIHelper.cpp
cpp/JSIHelper.h
cpp/SequelResult.h
cpp/react-native-quick-sqlite.cpp
cpp/sequel.cpp
cpp/sequel.h

Changes
- Created alternative implementation of SQLite Value Wrappers using regular Structs and Enums
- Converters to/from JSI Objects
- Regular executeSQL call switched to this implementation without any noticiable performance loss
- Implemented asyncExecuteSQL using JS Thread exclusivelly to convert data structures from parameters and reponses.
- Tested with more than 100 concurrent fetch queries and thousands of inserted rows using asyncLoadSQL File too.

Dynamic typing refactory and asyncExecuteSql working

---

android/CMakeLists.txt
cpp/installer.cpp
cpp/sqlbatchexecutor.cpp
cpp/sqlbatchexecutor.h
cpp/sqlfileloader.cpp
cpp/sqlfileloader.h
cpp/sqliteBridge.cpp
package.json
src/index.ts

- Method exported to its own file

Refactory of importSQLFile

---

android/CMakeLists.txt
android/build.gradle

Hi @ospfranco.
I removed this third party libraries that we are not using specifically in our project, and at least on my tests it works on Android Emulator and Physical Device, with and without Hermes.
It will be good to test in another projects too.

Removal of third party libraries not used in this project

---

cpp/sqlite3.h

- Important bugfix where querys with left joins and null
check on the right side can fetch incorrect results

SQLite upgrade to 3.38.2

---

README.md
cpp/JSIHelper.cpp
cpp/JSIHelper.h
cpp/installer.cpp
cpp/sqlbatchexecutor.cpp
cpp/sqliteBridge.cpp
cpp/sqliteBridge.h
src/index.ts

- Feature to return resultset metadata on the low level API
to help dynamic applications to analise column declared data types
that can be "different" from storage datatypes, like datetime or booleans

Resultset metadata

---

package.json
src/index.ts

A little change to Transaction API in order to remove the boolean return requirement.
A small fix to ensure that a failed transaction will not cause next transaction on the queue to be called.
A small fix that enhance the rows object to contain the "item" function that is described in their returned object documentation (QueryResult). It's only present in sqlexecution produced by IDBConnection implementation.

Little change on Transaction API and Method enhance fix

---

README.md
cpp/installer.cpp
cpp/sqliteBridge.cpp
cpp/sqliteBridge.h
src/index.ts

Despite the fact that attach or dettach a database can be performed
sending a simple SQL Statement, its easier for the attach process to
let the driver resolve the database document directory in order to create
or attach a existing database file.
Attach a different database may allow some tweaks, like
using different WAL modes or synchronization for each database, or
allow a more granular vacuum strategy.

Enable SQL Feature: SQL Attach and Dettach

---

cpp/sqlite3.h

- Add (long overdue) support for RIGHT and FULL OUTER JOIN.
- Add new binary comparison operators IS NOT DISTINCT FROM and IS DISTINCT FROM that are equivalent to IS and IS NOT, respective, for compatibility with PostgreSQL and SQL standards.
- Add a new return code (value "3") from the sqlite3_vtab_distinct() interface that indicates a query that has both DISTINCT and ORDER BY clauses.
- Added the sqlite3_db_name() interface.
- The unix os interface resolves all symbolic links in database filenames to create a canonical name for the database before the file is opened.
- Defer materializing views until the materialization is actually needed, thus avoiding unnecessary work if the materialization turns out to never be used.
- The HAVING clause of a SELECT statement is now allowed on any …

SQLite upgrade to version 3.39.0

---

README.md
cpp/installer.cpp
example/ios/Podfile
example/ios/Podfile.lock
example/package.json
example/src/App.tsx
example/src/Database.ts
ios/QuickSQLite.mm
package.json
src/index.ts

closes https://github.com/ospfranco/react-native-quick-sqlite/issues/59
@EduFrazao would you mind taking a look and doing a quick test?

Re-write the main binding to use a proxy object to avoid global scope

---

README.md
src/index.ts

closes #43 
@EduFrazao can you test if it is working properly on your end?

Add an async version of transactions

---

cpp/sqlite3.h

Fix an incorrect result from a query that uses a view that contains a compound SELECT in which only one arm contains a RIGHT JOIN and where the view is not the first FROM clause term of the query that contains the view. [forum post 174afeae5734d42d](https://sqlite.org/forum/forumpost/174afeae5734d42d).
Fix some harmless compiler warnings.
Fix a long-standing problem with [ALTER TABLE RENAME](https://www.sqlite.org/lang_altertable.html#altertabrename) that can only arise if the [sqlite3_limit](https://www.sqlite.org/c3ref/limit.html)([SQLITE_LIMIT_SQL_LENGTH](https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitsqllength)) is set to a very small value.
Fix a long-standing problem in [FTS3](https://www.sqlite.org/fts3.html) that can only arise when compiled with the …

SQLite upgraded to version 3.39.2

---

cpp/JSIHelper.cpp
cpp/sqliteBridge.cpp

These minor patches allow strings with NULL inside them to work properly in SQLite (like they do natively).
Currently, with NULL characters in-between strings (previously not possible in JavascriptCore due to a bug, but is functioning properly in Hermes engine), retrieving them would result in early truncation due to the way the `std::string`s were initialized at the locations addressed by the fix (initialized without length property).

fix: made retrieving TEXT columns from SQLite with NULL values in-between strings work properly

---

cpp/installer.cpp

`throwJSError` has been replaced by `throwOrDie` as per https://github.com/facebook/react-native/commit/0035cc9292aca15f07a9d2c51e3e340d5162d5e0
This works, but it break backward compatibility with RN < 0.70. What would be the best way to provide backward compatibility as well?

Make it compatible with React Native 0.70

---

cpp/installer.cpp

Removes the version dependent JSError throwing as discussed in https://github.com/ospfranco/react-native-quick-sqlite/pull/83 because the interface changed with https://github.com/facebook/react-native/commit/0035cc9292aca15f07a9d2c51e3e340d5162d5e0.
Tested on iOS with RN `0.67.4` and `0.70.0-rc.4` without errors.

Throw JSError React Native version independent

---

README.md
android/CMakeLists.txt
android/build.gradle

I've managed to enable FTS5 on both iOS and Android by specifying pre-processor flags.
On Android, we need to accept a setting from the parent project.
This PR makes it possible to specify SQLite flags via `android/gradle.properties`.
Also, I've added instructions on how to do that for iOS and Android.
Maybe the grammar could be improved tho.
fix #37

feat(ios&android): Support specifying pre-processor flags to sqlite

---

src/index.ts

Fixes to make optional parameter definitions to be more consistent.
```ts
db.transactionAsync(async (tx) => {
await tx.executeAsync('SELECT * FROM table1') // without specifying [] or undefined as second argument
}
```

Fix optional params consistency

---

cpp/sqlbatchexecutor.cpp

Added missing transaction rollback in case of SQL command errors reported by SQLite API in the middle of a batch execution.
Related to
#96

Rollback added in case of SQL Error reported by SQLite API.

---

example/src/tests/rawQueries.spec.ts
src/index.ts

See #111
The first commit is the core fix.
The second commit adds a promise to the `transactionAsync` method
- that resolves or rejects when the whole transaction finishes. 
- this allows calling code to know when a transaction is complete and not need to guess using setTimeout etc.
- It handles errors as well now.
Note: I did not add a promise the the `transaction` method - I am also unsure about the typeorm change.

Fix locks not working for multiple transactions started at the same time
